spring.application.name=foodservice
#spring.profiles.active=prod
spring.datasource.url=jdbc:mysql://localhost:3306/fdb
spring.datasource.username=root
spring.datasource.password={cipher}b9fb75af52fa830ffb4558a1d5ae726fba085db7a31ab72f03672caccfcdd4f4
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.hostname=localhost

#actuator configuration
management.endpoints.web.exposure.include=*

management.info.env.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
